# Syntax highlighting
highlighter: pygments
title: Kate Loginova
email: ekaterina.d.loginova@gmail.com
description: "I am Kate, a PhD student in educational data mining at Ghent University. I also work on natural language processing and digital journalism. If you want to collaborate, let me know!"
meta_author: Ekaterina Loginova
theme: minima
# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: disqus

include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Footer settings
# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: edloginova
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
url:                 http://edloginova.github.io
baseurl:             ""

minima:
 social_links:
    twitter: joealato
    github:  edloginova
    facebook: jekaterina.ld
    instagram: joealato
    linkedin: edloginova
    telegram: edloginova
    
social_research:
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Ekaterina_Loginova2'}
- {icon: 'google-scholar', link: 'https://scholar.google.ru/citations?hl=ru&user=PcfhhPQAAAAJ'}
- {icon: 'coursera', link: 'https://www.coursera.org/user/26c01e5fb55cff1cfd9cd458ed29f29b'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0002-0952-9213'}